// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('./components/Dialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCross: typeof import('./components/icons/IconCross.vue')['default']
    MainMenu: typeof import('./components/MainMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}

export {}
